"""Simulated annealing on the memory-packing problem.

Neighbours are generated by flipping H bits at once. A large H early keeps the
search mobile while the temperature is high; the geometric cooling schedule
then shrinks the accepted uphill moves until the walk settles.
"""

import argparse
import json
import os

import numpy as np

from problem import DIM, BUDGET, OBJECTIVES, report

T0 = 32 * 1024 * 1024
COOLING = 0.95
MAX_ITER = 100_000
RUNS = 20
FLIP_BITS = 8


def anneal(objective, rng, max_iter=MAX_ITER, t0=T0, cooling=COOLING, flip_bits=FLIP_BITS):
    """One annealing run. Returns (best_x, best_score, history)."""
    f = OBJECTIVES[objective]

    x = rng.integers(0, 2, DIM)
    fx = f(x)
    best_x, best_fx = x.copy(), fx

    temperature = t0
    history = np.empty(max_iter)

    for k in range(max_iter):
        candidate = x.copy()
        candidate[rng.choice(DIM, flip_bits, replace=False)] ^= 1
        f_candidate = f(candidate)

        delta = f_candidate - fx
        # Guard the exponent: at low temperature exp(-delta/T) underflows to 0,
        # which is the intended "reject" answer but warns if computed directly.
        if delta <= 0 or (temperature > 0 and rng.random() < np.exp(min(0.0, -delta / temperature))):
            x, fx = candidate, f_candidate

        if fx < best_fx:
            best_x, best_fx = x.copy(), fx

        history[k] = best_fx
        temperature *= cooling

    return best_x, best_fx, history


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--objective", choices=sorted(OBJECTIVES), default="slack")
    ap.add_argument("--runs", type=int, default=RUNS)
    ap.add_argument("--iterations", type=int, default=MAX_ITER)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    results_dir = os.path.join(here, "results")
    os.makedirs(results_dir, exist_ok=True)

    rng = np.random.default_rng(args.seed)
    histories, best_x, best_fx = [], None, float("inf")

    for run in range(args.runs):
        x, fx, history = anneal(args.objective, rng, max_iter=args.iterations)
        histories.append(history)
        if fx < best_fx:
            best_x, best_fx = x.copy(), fx
        print(f"run {run + 1:2d}/{args.runs}  best {fx}")

    summary = report(best_x, args.objective)
    # The reported score must be the score of the reported solution.
    assert summary["score"] == best_fx, "best solution and best score disagree"

    print(f"\nBest {args.objective}: {best_fx}")
    print(f"Selected {summary['selected']}/{DIM} requests, "
          f"{summary['total_bytes']:,} of {BUDGET:,} bytes, fits={summary['fits']}")

    summary["runs"] = args.runs
    summary["iterations"] = args.iterations
    summary["seed"] = args.seed
    with open(os.path.join(results_dir, f"annealing_{args.objective}.json"), "w") as f:
        json.dump(summary, f, indent=2)

    np.save(os.path.join(results_dir, f"annealing_{args.objective}_history.npy"),
            np.minimum.accumulate(np.array(histories), axis=1))


if __name__ == "__main__":
    main()
